### PR TITLE
Update Dockerfile.centos.7_9.x

### PR DESCRIPTION
**Pull request by mvaleev**
Remove yum cache data.

### CODE REVIEW

**Review by jbfavre — APPROVED** [review]
Thanks for you contribution !

**Comment by jbfavre** [comment]
hmmm, looks like `/bin/rm -f /var/cache/*` is a bit arsh.
@mvaleev could you have a look ? (I don't have any CentOS to check it right now

**Comment by mvaleev** [comment]
@jbfavre Ugh! My fail. 
Should be `/bin/rm -rf /tmp/vertica* /var/cache/*`

**Comment by jbfavre** [comment]
Is it relevant to delete everything in /var/cache ?
Not sure deleting lddconfig dir here is agood idea. What knid of infos you want to delete are stored here ?

**Comment by mvaleev** [comment]
Hmm. I never had a problem with that.  But for complete security, you can
only delete `/var/cache/yum`.

--
Best Regards,
Maxim Valeev

ср, 29 янв. 2020 г., 18:55 Jean Baptiste Favre <notifications@github.com>:

**Comment by jbfavre** [comment]
Should be fixed in commit 2af1fd1267508b610110db798893f9577392da3d

**Comment by sitingren** [comment]
Thanks for this quick bugfix!

**Pull request merged**
